const { Business } = require("../models");

const seedBusiness = () => Business.bulkCreate(dbBusinessData);

const dbBusinessData = [
  {
    title: "Sushi R US",
    description: "All your sushi needs",
    address: "111 First St",
    phone: "417-555-5555",
    site: "http://www.sushirus.com",
    hours: "",
    subCategory_id: 1,
  },
  {
    title: "Coffee Masters",
    description: "Best coffee in the world",
    address: "222 Second St",
    phone: "417-555-5555",
    site: "http://www.coffee.com",
    subCategory_id: 3,
  },
  {
    title: "taco world",
    description: "Taco Shop",
    address: "333 Third St",
    phone: "417-555-5555",
    site: "http://www.taco.com",
    subCategory_id: 2,
  },
  {
    title: "burger hut",
    description: "burgers and much more",
    address: "444 Biz St",
    phone: "417-555-5555",
    site: "http://www.burger.com",
    subCategory_id: 4,
  },
  {
    title: "Chicken TSO for life ",
    description: "best chinese ever",
    address: "555 Biz St",
    phone: "417-555-5555",
    site: "http://www.tso.com",
    subCategory_id: 5,
  },
  {
    title: "MOM Shop",
    description: "All you MOM Clothing Needs",
    address: "666 Biz St",
    phone: "417-555-5555",
    site: "http://www.MOMSRock.com",
    subCategory_id: 6,
  },
  {
    title: "Old Stuff Here",
    description: "Antiques",
    address: "777 Biz St",
    phone: "417-555-5555",
    site: "http://www.olderthebetter.com",
    subCategory_id: 7,
  },
  {
    title: "Hand Me Downs",
    description: "All the clothing your cuz brother used to have",
    address: "888 Biz St",
    phone: "417-555-5555",
    site: "http://www.notnewnomore.com",
    subCategory_id: 8,
  },
  {
    title: "Bobs Butcher",
    description: "Meat Meat and More Meat",
    address: "999 Biz St",
    phone: "417-555-5555",
    site: "http://www.cutthemup.com",
    subCategory_id: 9,
  },
  {
    title: "KC Drive In",
    description: "Dirve in movie theater",
    address: "1010 Biz St",
    phone: "417-555-5555",
    site: "http://www.diveinnotthrew.com",
    subCategory_id: 10,
  },
  {
    title: "Skate Park KC",
    description: "All Your Skating Needs",
    address: "1111 Biz St",
    phone: "417-555-5555",
    site: "http://www.skatemasters.com",
    subCategory_id: 11,
  },
  {
    title: "Futball",
    description: "Best sport in town",
    address: "1212 Biz St",
    phone: "417-555-5555",
    site: "http://www.roundballs.com",
    subCategory_id: 12,
  },
];

module.exports = seedBusiness;
